import type { CardDef } from './types'

// Card pool. The starter deck uses a subset; Bulwark and Power Surge live in
// the pool for a future reward/draft system (post-jam) without code changes.
export const CARDS: Record<string, CardDef> = {
  strike: {
    key: 'strike',
    name: 'Strike',
    cost: 1,
    type: 'attack',
    text: 'Deal 6 damage.',
    damage: 6,
  },
  quickjab: {
    key: 'quickjab',
    name: 'Quick Jab',
    cost: 0,
    type: 'attack',
    text: 'Deal 3 damage.',
    damage: 3,
  },
  ping: {
    key: 'ping',
    name: 'Ping',
    cost: 0,
    type: 'attack',
    text: 'Deal 2 damage. Draw 1.',
    damage: 2,
    draw: 1,
  },
  heavy: {
    key: 'heavy',
    name: 'Heavy Strike',
    cost: 2,
    type: 'attack',
    text: 'Deal 14 damage.',
    damage: 14,
  },
  powersurge: {
    key: 'powersurge',
    name: 'Power Surge',
    cost: 2,
    type: 'attack',
    text: 'Deal 14 damage. Your other attacks deal +3 this turn.',
    damage: 14,
    power: 3,
    powerTurns: 1,
  },
  expose: {
    key: 'expose',
    name: 'Expose',
    cost: 1,
    type: 'skill',
    text: 'Apply Vulnerable for 2 turns.',
    vulnerable: 2,
  },
  disrupt: {
    key: 'disrupt',
    name: 'Disrupt',
    cost: 1,
    type: 'skill',
    text: 'Apply Weak for 2 turns.',
    weak: 2,
  },
  corrupt: {
    key: 'corrupt',
    name: 'Corrupt',
    cost: 1,
    type: 'attack',
    text: 'Apply 4 Corruption. It bites each round, fading by 1.',
    corruption: 4,
  },
  leech: {
    key: 'leech',
    name: 'Leech',
    cost: 1,
    type: 'attack',
    text: 'Deal 5 damage. Heal 3.',
    damage: 5,
    heal: 3,
  },
  defend: {
    key: 'defend',
    name: 'Defend',
    cost: 1,
    type: 'skill',
    text: 'Gain 6 block.',
    block: 6,
  },
  bulwark: {
    key: 'bulwark',
    name: 'Bulwark',
    cost: 2,
    type: 'skill',
    text: 'Gain 12 block.',
    block: 12,
  },
  reroute: {
    key: 'reroute',
    name: 'Reroute',
    cost: 1,
    type: 'skill',
    text: 'Gain 4 block. Draw 1.',
    block: 4,
    draw: 1,
  },
  overclock: {
    key: 'overclock',
    name: 'Overclock',
    cost: 1,
    type: 'skill',
    text: 'Draw 2 cards.',
    draw: 2,
  },
  sever: {
    key: 'sever',
    name: 'Sever',
    cost: 1,
    type: 'skill',
    text: "Cut the Machine's link — it runs only scripted routines until restored. Exhaust.",
    sever: 2,
    exhaust: true,
  },
  // Reward-only cards (offered between trials, not in the starter deck).
  overload: {
    key: 'overload',
    name: 'Overload',
    cost: 2,
    type: 'attack',
    text: 'Deal 8 damage. Apply 2 Weak.',
    damage: 8,
    weak: 2,
  },
  reinforce: {
    key: 'reinforce',
    name: 'Reinforce',
    cost: 2,
    type: 'skill',
    text: 'Gain 8 block. Apply Vulnerable for 2 turns.',
    block: 8,
    vulnerable: 2,
  },
  firewall: {
    key: 'firewall',
    name: 'Firewall',
    cost: 2,
    type: 'skill',
    text: 'Gain 6 block. It lingers — gain 6 more next turn, stacking toward 12.',
    block: 6,
    retain: 6,
    linger: true,
  },
  loopback: {
    key: 'loopback',
    name: 'Loopback',
    cost: 1,
    type: 'attack',
    text: 'Deal 6 damage. Returns to your hand when you correctly Call an Imitation.',
    damage: 6,
    recur: true,
  },
  overdrive: {
    key: 'overdrive',
    name: 'Overdrive',
    cost: 1,
    type: 'skill',
    text: 'Your attacks deal +2 damage for 2 turns.',
    power: 2,
    powerTurns: 2,
  },
  bloodlink: {
    key: 'bloodlink',
    name: 'Bloodlink',
    cost: 1,
    type: 'skill',
    text: 'For 2 turns, your attacks heal you for half the damage they deal.',
    lifesteal: 2,
  },
  riposte: {
    key: 'riposte',
    name: 'Riposte',
    cost: 2,
    type: 'attack',
    text: 'Deal 8 damage. Gain 5 block.',
    damage: 8,
    block: 5,
  },
  overloadcore: {
    key: 'overloadcore',
    name: 'Overload Core',
    cost: 2,
    type: 'attack',
    text: 'Deal 16 damage. Lose 4 HP.',
    damage: 16,
    selfDamage: 4,
  },
  foresight: {
    key: 'foresight',
    name: 'Foresight',
    cost: 1,
    type: 'skill',
    text: 'Draw 3 cards.',
    draw: 3,
  },
  siphon: {
    key: 'siphon',
    name: 'Siphon',
    cost: 1,
    type: 'attack',
    text: 'Deal 5 damage. Draw 1.',
    damage: 5,
    draw: 1,
  },
}

// Cards offered as between-trial rewards (stronger than the starter set).
export const REWARD_POOL: string[] = [
  'powersurge',
  'bulwark',
  'overload',
  'reinforce',
  'firewall',
  'loopback',
  'overdrive',
  'bloodlink',
  'riposte',
  'overloadcore',
  'foresight',
  'siphon',
]

// 12-card starter deck: offense (Strike x3 / Quick Jab / Heavy), defense
// (Defend x3 / Reroute), cycle (Overclock), and the status pair (Expose / Disrupt).
export const STARTER_DECK: string[] = [
  'strike',
  'strike',
  'strike',
  'quickjab',
  'ping',
  'heavy',
  'defend',
  'defend',
  'defend',
  'reroute',
  'overclock',
  'expose',
  'disrupt',
  'corrupt',
  'leech',
]
